name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm run test
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: test_db
        DB_USER: postgres
        DB_PASSWORD: postgres
        JWT_SECRET: test-jwt-secret-key-for-ci
        JWT_REFRESH_SECRET: test-refresh-secret-key-for-ci

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Build Docker image
      run: |
        docker build -t school-sis:${{ github.sha }} .
        docker tag school-sis:${{ github.sha }} school-sis:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup deployment environment
      run: |
        echo "Setting up deployment environment..."
        echo "Environment: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Timestamp: $(date)"
    
    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        echo "Database configuration: ${DB_HOST}:${DB_PORT}/${DB_NAME}"
        echo "JWT configuration: $([ -n "${JWT_SECRET}" ] && echo "Configured" || echo "Missing")"
        echo "Encryption: $([ -n "${ENCRYPTION_KEY}" ] && echo "Configured" || echo "Missing")"
        echo "SMTP: $([ -n "${SMTP_HOST}" ] && echo "Configured" || echo "Missing")"
        
        # Add your deployment commands here
        # This could be deploying to AWS, DigitalOcean, etc.
        
        echo "✅ Deployment completed successfully!"
        echo "🚀 Application is now live in production"
      env:
        NODE_ENV: production
        # Database configuration
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        # JWT configuration
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        # Encryption
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        # SMTP configuration
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
